### This is the data given by data semantics in skillenza hackathon

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('TRAINING.csv')

In [3]:
df.head()

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Grade,Price
0,1,305,8.0,2.0,1.0,3.0,NO,0.0,76.0,2,63.0,4,D,3826$
1,2,344,6.0,7.0,7.0,8.0,no,0.0,83.0,7,97.0,1,B,4458$
2,3,294,8.0,4.0,3.0,4.0,yes,97.0,78.0,1,88.0,4,C,4199$
3,4,328,5.0,4.0,2.0,4.0,NO,0.0,91.0,5,86.0,1,D,3462$
4,5,295,9.0,5.0,3.0,5.0,NaN,NaN,97.0,4,93.0,3,C,4543$

### data preprocessing and data cleaning

In [8]:
#finding the null values
df.isnull().sum()

id             0
Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Grade          0
Price          0
dtype: int64

In [5]:
#mappping the values in attributes using one hot coding or you can use ordinal encoding 
f={'yes':1,'no':0,'YES':1,'NO':0}

In [6]:
df['roof']=df['roof'].map(f)

In [7]:
df.fillna(df.median(),inplace=True)

In [6]:
#import category_encoders as ce

In [7]:
#dfy=ce.OrdinalEncoder(cols=['roof'])
#dfa=dfy.fit_transform(df,['outcome'])
#dfa

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Grade,Price
0,1,305,8.0,2.0,1.0,3.0,1,0.0,76.0,2,63.0,4,D,3826$
1,2,344,6.0,7.0,7.0,8.0,2,0.0,83.0,7,97.0,1,B,4458$
2,3,294,8.0,4.0,3.0,4.0,3,97.0,78.0,1,88.0,4,C,4199$
3,4,328,5.0,4.0,2.0,4.0,1,0.0,91.0,5,86.0,1,D,3462$
4,5,295,9.0,5.0,3.0,5.0,4,0.0,97.0,4,93.0,3,C,4543$
5,6,335,8.0,6.0,5.0,7.0,1,0.0,99.0,6,75.0,1,C,4324$
6,7,322,9.0,4.0,1.0,3.0,5,112.0,78.0,4,65.0,4,C,4221$
7,8,346,8.0,3.0,2.0,4.0,1,0.0,87.0,2,72.0,4,D,3438$
8,9,298,5.0,5.0,4.0,6.0,4,0.0,103.0,6,62.0,2,D,3357$
9,10,329,5.0,7.0,7.0,8.0,4,0.0,79.0,6,67.0,3,B,4073$
10,11,304,6.0,7.0,5.0,7.0,4,0.0,81.0,8,76.0,6,B,4413$
11,12,305,8.0,8.0,5.0,7.0,4,0.0,94.0,8,99.0,4,A,4917$
12,13,298,8.0,6.0,4.0,6.0,1,0.0,94.0,5,97.0,4,C,4130$
13,14,307,6.0,4.0,1.0,3.0,5,83.0,106.0,1,61.0,1,D,3081$
14,15,329,6.0,4.0,4.0,5.0,2,0.0,90.0,3,89.0,2,D,3260$
15,16,316,7.0,2.0,2.0,3.0,4,0.0,86.0,3,80.0,4,D,3339$
16,17,351,6.0,5.0,6.0,7.0,3,72.0,106.0,6,80.0,6,C,4373$
17,18,312,7.0,3.0,2.0,4.0,2,0.0,103.0,4,99.0,2,D,3608$
18,19,318,5.0,3.0,3.0,5.0,2,0.0,80.0,3,79.0,5,D,3447$
19,20,359,9.0,5.0,4.0,6.0,3,92.0,106.0,6,80.0,2,B,4411$
20,21,346,8.0,8.0,6.0,8.0,3,77.0,89.0,8,91.0,5,A,5643$
21,22,339,6.0,4.0,3.0,4.0,4,0.0,103.0,3,69.0,3,D,3510$
22,23,304,8.0,7.0,6.0,8.0,3,94.0,92.0,8,90.0,3,A,5224$
23,24,291,6.0,4.0,1.0,3.0,4,0.0,80.0,3,60.0,2,D,3609$
24,25,313,5.0,2.0,3.0,4.0,4,0.0,104.0,2,96.0,4,D,3551$
25,26,348,6.0,4.0,5.0,6.0,3,108.0,87.0,4,80.0,5,C,4272$
26,27,349,8.0,6.0,4.0,6.0,2,0.0,73.0,6,87.0,6,B,4058$
27,28,328,7.0,5.0,5.0,6.0,2,0.0,107.0,6,66.0,3,C,3692$
28,29,318,6.0,5.0,3.0,5.0,5,102.0,72.0,5,68.0,1,D,3786$
29,30,357,9.0,6.0,5.0,6.0,4,0.0,75.0,4,62.0,3,B,4122$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6970,6971,354,6.0,4.0,1.0,3.0,5,93.0,93.0,3,73.0,4,D,3378$
6971,6972,350,6.0,3.0,2.0,3.0,5,120.0,85.0,3,84.0,5,C,3771$
6972,6973,333,7.0,4.0,1.0,3.0,5,107.0,72.0,4,59.0,5,D,3774$
6973,6974,320,6.0,2.0,1.0,3.0,4,0.0,78.0,2,68.0,6,D,3496$
6974,6975,297,9.0,6.0,6.0,8.0,5,111.0,92.0,5,78.0,6,B,4643$
6975,6976,311,9.0,5.0,5.0,6.0,3,100.0,70.0,7,99.0,6,B,4747$
6976,6977,308,5.0,3.0,3.0,4.0,3,85.0,80.0,5,63.0,4,D,3582$
6977,6978,340,7.0,5.0,5.0,7.0,1,0.0,90.0,4,86.0,3,C,4231$
6978,6979,356,8.0,6.0,7.0,8.0,1,0.0,107.0,6,60.0,1,B,4652$
6979,6980,307,6.0,8.0,6.0,7.0,2,0.0,106.0,7,98.0,6,B,4079$
6980,6981,301,6.0,5.0,4.0,5.0,3,110.0,101.0,3,75.0,4,D,4043$
6981,6982,292,8.0,7.0,6.0,7.0,2,0.0,90.0,6,64.0,4,C,4223$
6982,6983,359,8.0,5.0,5.0,6.0,5,89.0,79.0,3,75.0,2,C,4106$
6983,6984,312,6.0,3.0,3.0,5.0,4,0.0,87.0,5,84.0,6,D,3561$
6984,6985,322,9.0,3.0,1.0,3.0,2,0.0,79.0,1,96.0,5,C,3850$
6985,6986,290,7.0,3.0,1.0,3.0,5,102.0,94.0,1,92.0,5,D,3962$
6986,6987,329,5.0,7.0,5.0,7.0,1,0.0,102.0,7,79.0,2,C,4127$
6987,6988,324,8.0,6.0,4.0,5.0,2,0.0,98.0,6,79.0,4,C,3829$
6988,6989,343,9.0,5.0,6.0,7.0,2,0.0,101.0,7,69.0,3,B,4295$
6989,6990,313,6.0,4.0,4.0,6.0,4,0.0,71.0,5,88.0,2,D,3550$
6990,6991,296,8.0,8.0,5.0,7.0,5,92.0,96.0,5,86.0,6,B,4955$
6991,6992,303,9.0,6.0,6.0,7.0,5,116.0,103.0,5,97.0,3,B,4491$
6992,6993,295,8.0,4.0,1.0,3.0,2,0.0,105.0,1,81.0,4,D,3198$
6993,6994,335,6.0,3.0,2.0,3.0,5,93.0,102.0,1,59.0,5,D,3198$
6994,6995,314,7.0,7.0,5.0,6.0,3,99.0,72.0,5,98.0,3,C,4217$
6995,6996,306,8.0,2.0,1.0,3.0,4,0.0,78.0,1,73.0,5,D,3717$
6996,6997,341,5.0,3.0,2.0,4.0,5,100.0,72.0,4,76.0,4,D,3339$
6997,6998,306,6.0,4.0,2.0,4.0,3,83.0,80.0,4,96.0,4,D,3829$
6998,6999,338,8.0,7.0,6.0,7.0,1,0.0,95.0,4,84.0,1,B,4488$
6999,7000,314,5.0,6.0,4.0,6.0,3,109.0,80.0,4,96.0,2,C,3418$

In [10]:
df.isnull().sum()

id             0
Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Grade          0
Price          0
dtype: int64

In [11]:
df.dtypes

id               int64
Area(total)      int64
Troom          float64
Nbedrooms      float64
Nbwashrooms    float64
Twashrooms     float64
roof           float64
Roof(Area)     float64
Lawn(Area)     float64
Nfloors          int64
API            float64
ANB              int64
Grade           object
Price           object
dtype: object

In [12]:
df.describe(include='object')

       Grade  Price
count   7000   7000
unique     5   2042
top        C  3963$
freq    2928     15

In [13]:
df.roof.value_counts() / len(df.roof)

0.0    0.601143
1.0    0.398857
Name: roof, dtype: float64

In [14]:
df.roof.value_counts(normalize=True)

0.0    0.601143
1.0    0.398857
Name: roof, dtype: float64

In [15]:
df.roof.unique()

array([0., 1.])

In [17]:
#here we have removed $ symbol for the price attribute
df['Price'] = df['Price'].replace({'\$': '', ',': ''}, regex=True)

In [18]:
#convert to float for price
df['Price'] = df['Price'].astype(float)

In [19]:
df

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Grade,Price
0,1,305,8.0,2.0,1.0,3.0,0.0,0.0,76.0,2,63.0,4,D,3826.0
1,2,344,6.0,7.0,7.0,8.0,0.0,0.0,83.0,7,97.0,1,B,4458.0
2,3,294,8.0,4.0,3.0,4.0,1.0,97.0,78.0,1,88.0,4,C,4199.0
3,4,328,5.0,4.0,2.0,4.0,0.0,0.0,91.0,5,86.0,1,D,3462.0
4,5,295,9.0,5.0,3.0,5.0,0.0,0.0,97.0,4,93.0,3,C,4543.0
5,6,335,8.0,6.0,5.0,7.0,0.0,0.0,99.0,6,75.0,1,C,4324.0
6,7,322,9.0,4.0,1.0,3.0,1.0,112.0,78.0,4,65.0,4,C,4221.0
7,8,346,8.0,3.0,2.0,4.0,0.0,0.0,87.0,2,72.0,4,D,3438.0
8,9,298,5.0,5.0,4.0,6.0,0.0,0.0,103.0,6,62.0,2,D,3357.0
9,10,329,5.0,7.0,7.0,8.0,0.0,0.0,79.0,6,67.0,3,B,4073.0
10,11,304,6.0,7.0,5.0,7.0,0.0,0.0,81.0,8,76.0,6,B,4413.0
11,12,305,8.0,8.0,5.0,7.0,0.0,0.0,94.0,8,99.0,4,A,4917.0
12,13,298,8.0,6.0,4.0,6.0,0.0,0.0,94.0,5,97.0,4,C,4130.0
13,14,307,6.0,4.0,1.0,3.0,1.0,83.0,106.0,1,61.0,1,D,3081.0
14,15,329,6.0,4.0,4.0,5.0,0.0,0.0,90.0,3,89.0,2,D,3260.0
15,16,316,7.0,2.0,2.0,3.0,0.0,0.0,86.0,3,80.0,4,D,3339.0
16,17,351,6.0,5.0,6.0,7.0,1.0,72.0,106.0,6,80.0,6,C,4373.0
17,18,312,7.0,3.0,2.0,4.0,0.0,0.0,103.0,4,99.0,2,D,3608.0
18,19,318,5.0,3.0,3.0,5.0,0.0,0.0,80.0,3,79.0,5,D,3447.0
19,20,359,9.0,5.0,4.0,6.0,1.0,92.0,106.0,6,80.0,2,B,4411.0
20,21,346,8.0,8.0,6.0,8.0,1.0,77.0,89.0,8,91.0,5,A,5643.0
21,22,339,6.0,4.0,3.0,4.0,0.0,0.0,103.0,3,69.0,3,D,3510.0
22,23,304,8.0,7.0,6.0,8.0,1.0,94.0,92.0,8,90.0,3,A,5224.0
23,24,291,6.0,4.0,1.0,3.0,0.0,0.0,80.0,3,60.0,2,D,3609.0
24,25,313,5.0,2.0,3.0,4.0,0.0,0.0,104.0,2,96.0,4,D,3551.0
25,26,348,6.0,4.0,5.0,6.0,1.0,108.0,87.0,4,80.0,5,C,4272.0
26,27,349,8.0,6.0,4.0,6.0,0.0,0.0,73.0,6,87.0,6,B,4058.0
27,28,328,7.0,5.0,5.0,6.0,0.0,0.0,107.0,6,66.0,3,C,3692.0
28,29,318,6.0,5.0,3.0,5.0,1.0,102.0,72.0,5,68.0,1,D,3786.0
29,30,357,9.0,6.0,5.0,6.0,0.0,0.0,75.0,4,62.0,3,B,4122.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6970,6971,354,6.0,4.0,1.0,3.0,1.0,93.0,93.0,3,73.0,4,D,3378.0
6971,6972,350,6.0,3.0,2.0,3.0,1.0,120.0,85.0,3,84.0,5,C,3771.0
6972,6973,333,7.0,4.0,1.0,3.0,1.0,107.0,72.0,4,59.0,5,D,3774.0
6973,6974,320,6.0,2.0,1.0,3.0,0.0,0.0,78.0,2,68.0,6,D,3496.0
6974,6975,297,9.0,6.0,6.0,8.0,1.0,111.0,92.0,5,78.0,6,B,4643.0
6975,6976,311,9.0,5.0,5.0,6.0,1.0,100.0,70.0,7,99.0,6,B,4747.0
6976,6977,308,5.0,3.0,3.0,4.0,1.0,85.0,80.0,5,63.0,4,D,3582.0
6977,6978,340,7.0,5.0,5.0,7.0,0.0,0.0,90.0,4,86.0,3,C,4231.0
6978,6979,356,8.0,6.0,7.0,8.0,0.0,0.0,107.0,6,60.0,1,B,4652.0
6979,6980,307,6.0,8.0,6.0,7.0,0.0,0.0,106.0,7,98.0,6,B,4079.0
6980,6981,301,6.0,5.0,4.0,5.0,1.0,110.0,101.0,3,75.0,4,D,4043.0
6981,6982,292,8.0,7.0,6.0,7.0,0.0,0.0,90.0,6,64.0,4,C,4223.0
6982,6983,359,8.0,5.0,5.0,6.0,1.0,89.0,79.0,3,75.0,2,C,4106.0
6983,6984,312,6.0,3.0,3.0,5.0,0.0,0.0,87.0,5,84.0,6,D,3561.0
6984,6985,322,9.0,3.0,1.0,3.0,0.0,0.0,79.0,1,96.0,5,C,3850.0
6985,6986,290,7.0,3.0,1.0,3.0,1.0,102.0,94.0,1,92.0,5,D,3962.0
6986,6987,329,5.0,7.0,5.0,7.0,0.0,0.0,102.0,7,79.0,2,C,4127.0
6987,6988,324,8.0,6.0,4.0,5.0,0.0,0.0,98.0,6,79.0,4,C,3829.0
6988,6989,343,9.0,5.0,6.0,7.0,0.0,0.0,101.0,7,69.0,3,B,4295.0
6989,6990,313,6.0,4.0,4.0,6.0,0.0,0.0,71.0,5,88.0,2,D,3550.0
6990,6991,296,8.0,8.0,5.0,7.0,1.0,92.0,96.0,5,86.0,6,B,4955.0
6991,6992,303,9.0,6.0,6.0,7.0,1.0,116.0,103.0,5,97.0,3,B,4491.0
6992,6993,295,8.0,4.0,1.0,3.0,0.0,0.0,105.0,1,81.0,4,D,3198.0
6993,6994,335,6.0,3.0,2.0,3.0,1.0,93.0,102.0,1,59.0,5,D,3198.0
6994,6995,314,7.0,7.0,5.0,6.0,1.0,99.0,72.0,5,98.0,3,C,4217.0
6995,6996,306,8.0,2.0,1.0,3.0,0.0,0.0,78.0,1,73.0,5,D,3717.0
6996,6997,341,5.0,3.0,2.0,4.0,1.0,100.0,72.0,4,76.0,4,D,3339.0
6997,6998,306,6.0,4.0,2.0,4.0,1.0,83.0,80.0,4,96.0,4,D,3829.0
6998,6999,338,8.0,7.0,6.0,7.0,0.0,0.0,95.0,4,84.0,1,B,4488.0
6999,7000,314,5.0,6.0,4.0,6.0,1.0,109.0,80.0,4,96.0,2,C,3418.0

In [20]:
#split the data into x and y
x=df.drop('Grade',axis=1)
y=df['Grade']

In [43]:
x.head(3)

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Price
0,1,305,8.0,2.0,1.0,3.0,1,0.0,76.0,2,63.0,4,3826.0
1,2,344,6.0,7.0,7.0,8.0,2,0.0,83.0,7,97.0,1,4458.0
2,3,294,8.0,4.0,3.0,4.0,3,97.0,78.0,1,88.0,4,4199.0

In [21]:
x.shape

(7000, 13)

### xgboost model

In [22]:
from xgboost import XGBClassifier

In [23]:
 xgb = XGBClassifier()

In [24]:
 xgb

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [25]:
xgb.fit(x,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=22)

In [53]:
xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [28]:
y_test_pred = xgb.predict(x_test)

In [29]:
from sklearn import metrics

In [30]:
accuracy_before=metrics.accuracy_score(y_test,y_test_pred)
accuracy_before

0.8757142857142857

In [57]:
 from sklearn.model_selection import cross_val_score

In [32]:
from sklearn.model_selection import RandomizedSearchCV

In [33]:
xgb = XGBClassifier( n_estimators=100)

In [34]:
 param_grid= { "n_estimators"      : [100,1000],    
               "learning_rate"   : [0.1,0.001,0.2,0.3],             
               "nthread"       : [4,5,6,7,8,2],  
               "subsample" : [1.0],
               "max_depth"        : [6,8,9,5],
             "colsample_bytree"       :[0.5,0.8],
             "min_child_weight"  : [3,4],
             "reg_alpha"  : [0.03],
             "reg_lambda" : [1],
            }

In [35]:
 optimized_tree = RandomizedSearchCV(xgb, param_grid, scoring = 'accuracy', verbose=2, cv=5)

In [36]:
 optimized_tree.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8, total=   1.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.3s remaining:    0.0s

[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8, total=   1.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8, total=   1.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8, total=   1.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=7, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.8, total=   1.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5, total=   8.6s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5, total=  11.9s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5, total=  12.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5, total=  12.1s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=1000, min_child_weight=3, max_depth=6, learning_rate=0.3, colsample_bytree=0.5, total=  10.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=   2.1s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=   2.0s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=   2.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=   1.9s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=4, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=   2.5s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=  10.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=  11.0s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=  10.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=  10.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=1000, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.5, total=  10.6s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=5, learning_rate=0.1, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  43.5s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  26.9s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8

[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  24.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  24.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=2, n_estimators=1000, min_child_weight=3, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  27.0s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8, total=   2.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8, total=   2.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8, total=   2.3s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8, total=   2.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=100, min_child_weight=4, max_depth=9, learning_rate=0.001, colsample_bytree=0.8, total=   2.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  27.2s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  26.8s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  27.6s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  23.0s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=5, n_estimators=1000, min_child_weight=4, max_depth=8, learning_rate=0.001, colsample_bytree=0.8, total=  22.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8, total=   1.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8, total=   1.8s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8, total=   1.8s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8, total=   1.9s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=6, n_estimators=100, min_child_weight=3, max_depth=9, learning_rate=0.3, colsample_bytree=0.8, total=   2.0s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5, total=   1.7s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5, total=   1.6s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5, total=   1.4s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5, total=   1.1s
[CV] subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5
[CV]  subsample=1.0, reg_lambda=1, reg_alpha=0.03, nthread=8, n_estimators=100, min_child_weight=3, max_depth=5, learning_rate=0.3, colsample_bytree=0.5, total=   1.7s

[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:  7.6min finished

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'n_estimators': [100, 1000], 'learning_rate': [0.1, 0.001, 0.2, 0.3], 'nthread': [4, 5, 6, 7, 8, 2], 'subsample': [1.0], 'max_depth': [6, 8, 9, 5], 'colsample_bytree': [0.5, 0.8], 'min_child_weight': [3, 4], 'reg_alpha': [0.03], 'reg_lambda': [1]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring='accuracy', verbose=2)

In [37]:
 optimized_tree.best_params_

{'subsample': 1.0,
 'reg_lambda': 1,
 'reg_alpha': 0.03,
 'nthread': 8,
 'n_estimators': 1000,
 'min_child_weight': 3,
 'max_depth': 6,
 'learning_rate': 0.3,
 'colsample_bytree': 0.5}

In [38]:
 y_test_pred=optimized_tree.predict(x_test)

### accuracy after tuning

In [39]:
 metrics.accuracy_score(y_test, y_test_pred)

0.871904761904762

### load the test and clean the test data as well or testing it with model you built

In [41]:
test=pd.read_csv('TEST.CSV')
test.head()

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Price
0,1,348,9.0,5.0,3.0,5,NaN,NaN,84.0,5,91.0,6,4422$
1,2,311,6.0,5.0,5.0,6,NO,0.0,86.0,6,83.0,4,3432$
2,3,342,5.0,6.0,6.0,7,yes,120.0,85.0,4,95.0,5,4066$
3,4,329,7.0,7.0,4.0,6,NaN,NaN,105.0,5,97.0,6,4322$
4,5,307,6.0,2.0,3.0,4,no,0.0,76.0,2,64.0,4,3031$

In [46]:
test.isnull().sum()

id             0
Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Price          0
dtype: int64

In [43]:
g={'yes':1,'no':0,'YES':1,'NO':0}

In [44]:
test['roof']=test['roof'].map(g)

In [45]:
test.fillna(test.median(),inplace=True)

In [47]:
test.head()

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Price
0,1,348,9.0,5.0,3.0,5,0.0,0.0,84.0,5,91.0,6,4422$
1,2,311,6.0,5.0,5.0,6,0.0,0.0,86.0,6,83.0,4,3432$
2,3,342,5.0,6.0,6.0,7,1.0,120.0,85.0,4,95.0,5,4066$
3,4,329,7.0,7.0,4.0,6,0.0,0.0,105.0,5,97.0,6,4322$
4,5,307,6.0,2.0,3.0,4,0.0,0.0,76.0,2,64.0,4,3031$

In [48]:
#df1=ce.OrdinalEncoder(cols=['roof'])
#df2=df1.fit_transform(test,['outcome'])
#df2.head()

In [49]:
test['Price'] = test['Price'].replace({'\$': '', ',': ''}, regex=True)

In [54]:
test['Price'] = test['Price'].astype(float)

In [55]:
test.head()

,id,Area(total),Troom,Nbedrooms,Nbwashrooms,Twashrooms,roof,Roof(Area),Lawn(Area),Nfloors,API,ANB,Price
0,1,348,9.0,5.0,3.0,5,0.0,0.0,84.0,5,91.0,6,4422.0
1,2,311,6.0,5.0,5.0,6,0.0,0.0,86.0,6,83.0,4,3432.0
2,3,342,5.0,6.0,6.0,7,1.0,120.0,85.0,4,95.0,5,4066.0
3,4,329,7.0,7.0,4.0,6,0.0,0.0,105.0,5,97.0,6,4322.0
4,5,307,6.0,2.0,3.0,4,0.0,0.0,76.0,2,64.0,4,3031.0

In [56]:
test.isnull().sum()

id             0
Area(total)    0
Troom          0
Nbedrooms      0
Nbwashrooms    0
Twashrooms     0
roof           0
Roof(Area)     0
Lawn(Area)     0
Nfloors        0
API            0
ANB            0
Price          0
dtype: int64

In [57]:
Grade=optimized_tree.predict(test)

In [58]:
sample=pd.DataFrame({'id':test.id,'Grade':Grade},index=None)

### sample output looks

In [60]:
sample.to_csv('datasematics_final.csv',index=False)

In [61]:
sample=pd.read_csv('datasematics_final.csv')
sample

        id Grade
0        1     B
1        2     D
2        3     C
3        4     C
4        5     D
5        6     C
6        7     B
7        8     C
8        9     D
9       10     D
10      11     D
11      12     D
12      13     D
13      14     D
14      15     C
15      16     C
16      17     B
17      18     B
18      19     C
19      20     C
20      21     B
21      22     D
22      23     C
23      24     B
24      25     D
25      26     C
26      27     B
27      28     C
28      29     B
29      30     C
...    ...   ...
3269  3270     C
3270  3271     B
3271  3272     D
3272  3273     C
3273  3274     C
3274  3275     A
3275  3276     C
3276  3277     C
3277  3278     D
3278  3279     B
3279  3280     C
3280  3281     C
3281  3282     C
3282  3283     D
3283  3284     C
3284  3285     D
3285  3286     D
3286  3287     C
3287  3288     B
3288  3289     D
3289  3290     C
3290  3291     D
3291  3292     C
3292  3293     D
3293  3294     D
3294  3295     C
3295  3296     D
3296  3297     C
3297  3298     C
3298  3299     D

[3299 rows x 2 columns]